[package]
authors     = ["Oracol XOR Network <contact@oracol.org>"]
build       = "build.rs"
description = "Oracol node"
edition     = "2018"
homepage    = "https://oracol.org/"
license     = "GPL-3.0"
name        = "xor"
readme      = "README.md"
repository  = "https://github.com/ProjectXOR/oracol-node"
version     = "0.0.1"

# TODO: Consider rename this repo to oracol-runtime-module-library
[[bin]]
name = "xor"

[dependencies]
# crates
array-bytes    = { version = "1.1.0" }
codec          = { package = "parity-scale-codec", version = "2.0.1" }
futures        = { version = "0.3.13" }
jsonrpc-core   = { version = "15.1.0" }
jsonrpc-pubsub = { version = "15.1.0" }
log            = { version = "0.4.14" }
structopt      = { version = "0.3.21" }
tokio          = { version = "0.3.6", optional = true, features = ["rt-multi-thread"] }
# oracol
oracol-balances-rpc               = { path = "../../../frame/balances/rpc" }
oracol-balances-rpc-runtime-api   = { path = "../../../frame/balances/rpc/runtime-api" }
oracol-claims                     = { path = "../../../frame/claims" }
oracol-cli                        = { optional = true, path = "../../../client/cli" }
oracol-ethereum-relay             = { path = "../../../frame/bridge/ethereum/relay" }
oracol-evm                        = { path = "../../../frame/evm" }
oracol-header-mmr-rpc             = { path = "../../../frame/header-mmr/rpc" }
oracol-header-mmr-rpc-runtime-api = { path = "../../../frame/header-mmr/rpc/runtime-api" }
oracol-staking                    = { path = "../../../frame/staking" }
oracol-staking-rpc                = { path = "../../../frame/staking/rpc" }
oracol-staking-rpc-runtime-api    = { path = "../../../frame/staking/rpc/runtime-api" }
dc-db                               = { path = "../../../client/dvm/db" }
dc-mapping-sync                     = { path = "../../../client/dvm/mapping-sync" }
dc-rpc                              = { path = "../../../client/dvm/rpc", features = ["rpc_binary_search_estimate"] }
dp-rpc                              = { path = "../../../primitives/rpc" }
dp_consensus                        = { path = "../../../primitives/consensus" }
xor-primitives                     = { path = "../primitives" }
dvm-ethereum                        = { path = "../../../frame/dvm" }
dvm-rpc-runtime-api                 = { path = "../../../frame/dvm/rpc/runtime-api" }
oracol-runtime                    = { path = "../runtime/oracol" }
# substrate
frame-system-rpc-runtime-api               = { git = "https://github.com/ProjectXOR/substrate.git", branch = "latest" }
pallet-im-online                           = { git = "https://github.com/ProjectXOR/substrate.git", branch = "latest" }
pallet-transaction-payment-rpc             = { git = "https://github.com/ProjectXOR/substrate.git", branch = "latest" }
pallet-transaction-payment-rpc-runtime-api = { git = "https://github.com/ProjectXOR/substrate.git", branch = "latest" }
sc-authority-discovery                     = { git = "https://github.com/ProjectXOR/substrate.git", branch = "latest" }
sc-basic-authorship                        = { git = "https://github.com/ProjectXOR/substrate.git", branch = "latest" }
sc-chain-spec                              = { git = "https://github.com/ProjectXOR/substrate.git", branch = "latest" }
sc-cli                                     = { optional = true, git = "https://github.com/ProjectXOR/substrate.git", branch = "latest" }
sc-client-api                              = { git = "https://github.com/ProjectXOR/substrate.git", branch = "latest" }
sc-consensus                               = { git = "https://github.com/ProjectXOR/substrate.git", branch = "latest" }
sc-consensus-babe                          = { git = "https://github.com/ProjectXOR/substrate.git", branch = "latest" }
sc-consensus-babe-rpc                      = { git = "https://github.com/ProjectXOR/substrate.git", branch = "latest" }
sc-consensus-epochs                        = { git = "https://github.com/ProjectXOR/substrate.git", branch = "latest" }
sc-consensus-slots                         = { git = "https://github.com/ProjectXOR/substrate.git", branch = "latest" }
sc-executor                                = { git = "https://github.com/ProjectXOR/substrate.git", branch = "latest" }
sc-finality-grandpa                        = { git = "https://github.com/ProjectXOR/substrate.git", branch = "latest" }
sc-finality-grandpa-rpc                    = { git = "https://github.com/ProjectXOR/substrate.git", branch = "latest" }
sc-finality-grandpa-warp-sync              = { optional = true, git = "https://github.com/ProjectXOR/substrate.git", branch = "latest" }
sc-keystore                                = { git = "https://github.com/ProjectXOR/substrate.git", branch = "latest" }
sc-network                                 = { git = "https://github.com/ProjectXOR/substrate.git", branch = "latest" }
sc-rpc                                     = { git = "https://github.com/ProjectXOR/substrate.git", branch = "latest" }
sc-service                                 = { optional = true, git = "https://github.com/ProjectXOR/substrate.git", branch = "latest" }
sc-sync-state-rpc                          = { git = "https://github.com/ProjectXOR/substrate.git", branch = "latest" }
sc-telemetry                               = { git = "https://github.com/ProjectXOR/substrate.git", branch = "latest" }
sc-transaction-pool                        = { git = "https://github.com/ProjectXOR/substrate.git", branch = "latest" }
sp-api                                     = { git = "https://github.com/ProjectXOR/substrate.git", branch = "latest" }
sp-authority-discovery                     = { git = "https://github.com/ProjectXOR/substrate.git", branch = "latest" }
sp-block-builder                           = { git = "https://github.com/ProjectXOR/substrate.git", branch = "latest" }
sp-blockchain                              = { git = "https://github.com/ProjectXOR/substrate.git", branch = "latest" }
sp-consensus                               = { git = "https://github.com/ProjectXOR/substrate.git", branch = "latest" }
sp-consensus-babe                          = { git = "https://github.com/ProjectXOR/substrate.git", branch = "latest" }
sp-core                                    = { git = "https://github.com/ProjectXOR/substrate.git", branch = "latest" }
sp-finality-grandpa                        = { git = "https://github.com/ProjectXOR/substrate.git", branch = "latest" }
sp-inherents                               = { git = "https://github.com/ProjectXOR/substrate.git", branch = "latest" }
sp-keystore                                = { git = "https://github.com/ProjectXOR/substrate.git", branch = "latest" }
sp-offchain                                = { git = "https://github.com/ProjectXOR/substrate.git", branch = "latest" }
sp-runtime                                 = { git = "https://github.com/ProjectXOR/substrate.git", branch = "latest" }
sp-session                                 = { git = "https://github.com/ProjectXOR/substrate.git", branch = "latest" }
sp-transaction-pool                        = { git = "https://github.com/ProjectXOR/substrate.git", branch = "latest" }
sp-trie                                    = { features = ["memory-tracker"], git = "https://github.com/ProjectXOR/substrate.git", branch = "latest" }
substrate-frame-rpc-system                 = { git = "https://github.com/ProjectXOR/substrate.git", branch = "latest" }
substrate-prometheus-endpoint              = { git = "https://github.com/ProjectXOR/substrate.git", branch = "latest" }
try-runtime-cli                            = { optional = true, git = "https://github.com/ProjectXOR/substrate.git", branch = "latest" }

[build-dependencies]
# substrate
substrate-build-script-utils = { git = "https://github.com/ProjectXOR/substrate.git", branch = "latest" }
try-runtime-cli              = { optional = true, git = "https://github.com/ProjectXOR/substrate.git", branch = "latest" }

[features]
default = [
	"cli",
	"db",
	"full-node",
	"wasmtime",
]

cli       = [
	"tokio",
	"oracol-cli",
	"sc-cli",
	"sc-finality-grandpa-warp-sync",
	"sc-service",
]
db        = ["sc-service/db"]
full-node = []
wasmtime  = ["sc-cli/wasmtime"]
# Enable features that allow the runtime to be tried and debugged. Name might be subject to change
# in the near future.
try-runtime = [
	"oracol-runtime/try-runtime",
	"try-runtime-cli",
]
