[package]
authors     = ["Oracol XOR Network <contact@oracol.org>"]
description = "FRAME pallet to back Ethereum assets"
edition     = "2018"
homepage    = "https://oracol.org/"
license     = "GPL-3.0"
name        = "oracol-ethereum-issuing-contract"
readme      = "README.md"
repository  = "https://github.com/ProjectXOR/oracol-node"
version     = "0.0.1"

[dependencies]
# crates
ethereum-types = { default-features = false, version = "0.11.0" }
# github
ethabi = { default-features = false, git = "https://github.com/ProjectXOR/ethabi.git", branch = "xavier-no-std" }

[features]
default = ["std"]

std = [
	"crates-std",
	"github-std",
]

crates-std = [
	"ethereum-types/std",
]
github-std = [
	"ethabi/std",
]
