[package]
authors     = ["Oracol XOR Network <contact@oracol.org>"]
description = "Issuing precompile for EVM pallet."
edition     = "2018"
homepage    = "https://oracol.org/"
license     = "GPL-3.0"
name        = "oracol-evm-precompile-issuing"
readme      = "README.md"
repository  = "https://github.com/ProjectXOR/oracol-node"
version     = "0.0.1"

[dependencies]
# crates
evm = { default-features = false, version = "0.25.0", features = ["with-codec"] }
# oracol
oracol-evm = { default-features = false, path = "../../../" }
dp-evm       = { default-features = false, path = "../../../../../primitives/evm" }

[features]
default = ["std"]

std = [
	"crates-std",
	"oracol-std",
]

crates-std = [
	"evm/std",
]

oracol-std = [
	"oracol-evm/std",
	"dp-evm/std",
]
