[package]
authors     = ["Oracol XOR Network <contact@oracol.org>"]
description = "DISPATCH precompiles for EVM pallet."
edition     = "2018"
homepage    = "https://oracol.org/"
license     = "GPL-3.0"
name        = "oracol-evm-precompile-dispatch"
readme      = "README.md"
repository  = "https://github.com/ProjectXOR/oracol-node"
version     = "0.0.1"


[dependencies]
# crates
codec        = { package = "parity-scale-codec", version = "2.0.1", default-features = false }
oracol-evm = { default-features = false, path = "../../../../evm" }
dp-evm       = { default-features = false, path = "../../../../../primitives/evm" }
evm          = { version = "0.25.0", default-features = false, features = ["with-codec"] }
# substrate
frame-support = { default-features = false, git = "https://github.com/ProjectXOR/substrate.git", branch = "latest" }
sp-core       = { default-features = false, git = "https://github.com/ProjectXOR/substrate.git", branch = "latest" }
sp-io         = { default-features = false, git = "https://github.com/ProjectXOR/substrate.git", branch = "latest" }

[features]
default = ["std"]

std = [
	"crates-std",
	"substrate-std",
]

crates-std = [
	"codec/std",
	"oracol-evm/std",
	"dp-evm/std",
	"evm/std",
]

substrate-std = [
	"frame-support/std",
	"sp-core/std",
	"sp-io/std",
]
