[package]
authors     = ["Oracol XOR Network <contact@oracol.org>"]
description = "Withdraw precompile for EVM pallet."
edition     = "2018"
homepage    = "https://oracol.org/"
license     = "GPL-3.0"
name        = "oracol-evm-precompile-withdraw"
readme      = "README.md"
repository  = "https://github.com/ProjectXOR/oracol-node"
version     = "0.0.1"

[dependencies]
# crates
codec     = { package = "parity-scale-codec", version = "2.0.1", default-features = false }
evm       = { version = "0.25.0", features = ["with-codec"], default-features = false }
ripemd160 = { version = "0.9", default-features = false }
# oracol
oracol-evm     = { default-features = false, path = "../../../" }
oracol-support = { default-features = false, path = "../../../../support" }
dp-evm           = { default-features = false, path = "../../../../../primitives/evm" }
# substrate
frame-support    = { default-features = false, git = "https://github.com/ProjectXOR/substrate.git", branch = "latest" }
frame-system     = { default-features = false, git = "https://github.com/ProjectXOR/substrate.git", branch = "latest" }
pallet-timestamp = { default-features = false, git = "https://github.com/ProjectXOR/substrate.git", branch = "latest" }
sp-core          = { default-features = false, git = "https://github.com/ProjectXOR/substrate.git", branch = "latest" }
sp-io            = { default-features = false, git = "https://github.com/ProjectXOR/substrate.git", branch = "latest" }
sp-runtime       = { default-features = false, git = "https://github.com/ProjectXOR/substrate.git", branch = "latest" }
sp-std           = { default-features = false, git = "https://github.com/ProjectXOR/substrate.git", branch = "latest" }

[features]
default = ["std"]

std = [
	"crates-std",
	"oracol-std",
	"substrate-std",
]

crates-std = [
	"codec/std",
	"evm/std",
	"ripemd160/std",
]

oracol-std = [
	"oracol-evm/std",
	"oracol-support/std",
	"dp-evm/std",
]

substrate-std = [
	"frame-support/std",
	"frame-system/std",
	"pallet-timestamp/std",
	"sp-core/std",
	"sp-io/std",
	"sp-runtime/std",
	"sp-std/std",
]
