[package]
authors     = ["Oracol XOR Network <contact@oracol.org>"]
description = "BLAKE2 precompiles for EVM pallet."
edition     = "2018"
homepage    = "https://oracol.org/"
license     = "GPL-3.0"
name        = "oracol-evm-precompile-blake2"
readme      = "README.md"
repository  = "https://github.com/ProjectXOR/oracol-node"
version     = "0.0.1"


[dependencies]
# crates
dp-evm = { default-features = false, path = "../../../../../primitives/evm" }
evm    = { version = "0.25.0", default-features = false, features = ["with-codec"] }
# substrate
sp-core = { default-features = false, git = "https://github.com/ProjectXOR/substrate.git", branch = "latest" }
sp-io   = { default-features = false, git = "https://github.com/ProjectXOR/substrate.git", branch = "latest" }

[features]
default = ["std"]

std = [
	"crates-std",
	"substrate-std",
]

crates-std = [
	"evm/std",
	"dp-evm/std",
]

substrate-std = [
	"sp-core/std",
	"sp-io/std",
]
