[package]
authors     = ["Oracol XOR Network <contact@oracol.org>"]
description = "Empty mock precompiles for EVM pallet."
edition     = "2018"
homepage    = "https://oracol.org/"
license     = "GPL-3.0"
name        = "oracol-evm-precompile-empty"
readme      = "README.md"
repository  = "https://github.com/ProjectXOR/oracol-node"
version     = "0.0.1"

[dependencies]
# crates
dp-evm = { default-features = false, path = "../../../../../primitives/evm" }
evm    = { version = "0.25.0", default-features = false, features = ["with-codec"] }

[features]
default = ["std"]

std = [
	"crates-std",
]

crates-std = [
	"dp-evm/std",
	"evm/std",
]
